language: php
sudo: false

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --no-interaction

stages:
  - phpstan analysis
  - check style

script:
  - composer phpstan-analysis

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - stage: phpstan analysis
      php: 7.2
      script:
        - composer phpstan-analysis
    - stage: check style
      php: 7.2
      script:
        - composer check-style

